apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hostpath
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hostpath
  template:
    metadata:
      labels:
        app: nginx-hostpath
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.2
        volumeMounts:
        - name: hostpath-volume
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: hostpath-volume
        hostPath:
          path: /mnt/hostPath
          type: DirectoryOrCreate