name: CI/CD Pipeline

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 test:
   runs-on: ubuntu-latest
   
   services:
     redis:
       image: redis
       ports:
         - 6379:6379
         
   defaults:
     run:
       working-directory: ./userapi
         
   steps:
   - uses: actions/checkout@v2
   
   - name: Setup Node.js
     uses: actions/setup-node@v2
     with:
       node-version: '16.x'
       
   - name: Install Dependencies
     run: |
       npm install -g mocha
       npm install
     
   - name: Run Tests
     run: npm test

   - name: Build Docker image
     run: docker build -t ngansom/userapi .
     
   - name: Login to Docker Hub
     uses: docker/login-action@v1
     with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       
   - name: Push Docker image
     run: docker push ngansom/userapi